### ISSUE TITLE
snmp request "IO WAIT" issues observed after pr #277

### ISSUE THREAD

**Issue by vorlon001** [gosnmp/gosnmp#285] opened 2021-01-19 22:20 UTC
AFTER COMMIT https://github.com/gosnmp/gosnmp/pull/277

very bad commit
this one did not work at all
After commit 70% snmp reuest "IO WAIT"
SNMP V2 udp on port 161 not work after this commit
70-90% snmp get ERROR "IO WAIT"

**Comment by vorlon001** [comment] 2021-01-19 22:23
https://github.com/gosnmp/gosnmp/commit/b4bea65e80c1c59e228bd0f7b3de63f634166c9b
70-90% snmp get ERROR "IO WAIT"

**Comment by theraphim** [comment] 2021-01-20 17:12
Did you actually enable new functionality? because this commit should be a no-op if you don't enable UseUnconnectedUDPSocket.

Is it possible to know more about your environment?

**Comment by TimRots** [comment] 2021-01-20 17:47
Hi @vorlon001. Thank you for reporting an issue. 

As @theraphim stated, would you be able to share as much info as possible about your environment (and if possible code) for us to reproduce the issue you are observing?

**Comment by vorlon001** [comment] 2021-01-21 06:19
this code is change
I start collecting 600 devices at once
if you use GOSNMP October 2020 then there are no errors

[https://cloud.mail.ru/public/7t3v/X3C8Ywk8b](url)
[https://cloud.mail.ru/public/24Ar/fUxUzocnn](url)

**Comment by SuperQ** [comment] 2021-01-21 17:10
This change has not been released yet. For compliance you should not be running unreleased code.

**Comment by theraphim** [comment] 2021-01-21 18:38
@vorlon001 this is strange. The only reason I can imagine this is going bad is on the receive path, standard udp socket is type-asserted into packetconn, then for some reason RecvFrom isn't working.

Can you try applying https://github.com/theraphim/gosnmp/commit/5df267f49895b2f63a98dc1d009f00c9582f8791 and testing again? if it helps, we'll know where the problem is.

Thanks!

**Comment by vorlon001** [comment] 2021-01-22 19:01
>Can you try applying theraphim@5df267f and testing again? if it helps, we'll know where the problem is.
yes i test current version from github its not work
i use version from october 2020 - work - correct

**Comment by theraphim** [comment] 2021-01-22 19:36
Well, then I'm afraid I can't do anything useful if I have no information.

@SuperQ @TimRots can we, in spirit of being paranoidly backward-compatible, apply the patch I referred above? If yes I'll turn it into a PR. As you can see, it's just a refactoring which will make it impossible to even accidentally land on the code that does RecvFrom on connected socket.

**Comment by vorlon001** [comment] 2021-01-23 04:16
@theraphim  sorry this code dos not work correct

OS: Debian 9.13
`        if uconn, ok := x.Conn.(net.PacketConn); ok {
                n, _, err = uconn.ReadFrom(x.rxBuf[:]) - This LINE
        } else {
                n, err = x.Conn.Read(x.rxBuf[:])
        }`

`ERROR 10.100.1.1, <nil>
         map[ip:10.100.1.1 model:]
                request timeout (after 0 retries)
2021/01/23 09:11:33
Internal error: goroutine 527 [running]:
main.panicRecoverWorker(0x7ced46, 0xd, 0xc0014524e8, 0xc00005e480)
        <REMOVE>/panic_module.go:24 +0x8f
panic(0x76d3e0, 0xa095d0)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
main.(*WorkerDevice).GetDevice(0xc001339360)
        <REMOVE>/bshpd_worker.go:367 +0x85a
created by main.(*WorkerJoin).Run
        <REMOVE>/bshpd_worker.go:485 +0x390

goroutine 1 [chan receive]:
main.(*WorkerJoin).Run(0xc0001d0000)
        <REMOVE>/bshpd_worker.go:491 +0x425
main.JOBS()
        <REMOVE>/main23.go:26 +0x225
main.main()
        <REMOVE>/main23.go:33 +0x25

goroutine 6 [chan receive]:
github.com/ClickHouse/clickhouse-go.init.0.func1()
        /root/go/src/github.com/ClickHouse/clickhouse-go/bootstrap.go:50 +0x4b
created by github.com/ClickHouse/clickhouse-go.init.0
        /root/go/src/github.com/ClickHouse/clickhouse-go/bootstrap.go:47 +0x66

goroutine 365 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7ff808c77120, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc002d23c98, 0x72, 0xff00, 0xffff, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).ReadFrom(0xc002d23c80, 0xc004f26000, 0xffff, 0xffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:215 +0x1c5
net.(*netFD).readFrom(0xc002d23c80, 0xc004f26000, 0xffff, 0xffff, 0xc002d23c80, 0x58, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_posix.go:61 +0x5b
net.(*UDPConn).readFrom(0xc0013aa608, 0xc004f26000, 0xffff, 0xffff, 0x40f0e8, 0x7ff808cc1bd0, 0xc00372f9d0, 0x40cdaa)
        /usr/local/go/src/net/udpsock_posix.go:47 +0x5c
net.(*UDPConn).ReadFrom(0xc0013aa608, 0xc004f26000, 0xffff, 0xffff, 0xc0013aa608, 0xc002d23c01, 0xc0025dd0a0, 0x58, 0xd6)
        /usr/local/go/src/net/udpsock.go:118 +0x5d
_<REMOVE>/gosnmp.(*GoSNMP).receive(0xc002798a00, 0xc002781e50, 0x58, 0xd6, 0x58, 0x0)
        <REMOVE>/gosnmp/marshal.go:1176 +0x98
_<REMOVE>/gosnmp.(*GoSNMP).sendOneRequest(0xc002798a00, 0xc0027dc540, 0x1, 0xfa, 0x0, 0x81ed4e)
        <REMOVE>/gosnmp/marshal.go:239 +0x5cf
_<REMOVE>/gosnmp.(*GoSNMP).send(0xc002798a00, 0xc0027dc540, 0xc0025cb301, 0x0, 0x0, 0x0)
        <REMOVE>/gosnmp/marshal.go:371 +0xf1
_<REMOVE>/gosnmp.(*GoSNMP).Get(0xc002798a00, 0xc00001e4c0, 0x3, 0x4, 0x0, 0xc000e04cf0, 0x75a1c0)
        <REMOVE>/gosnmp/gosnmp.go:413 +0x159
main.(*WorkerDevice).GetDevice(0xc001ed6dc0)
        <REMOVE>/bshpd_worker.go:313 +0x6ed
created by main.(*WorkerJoin).Run
        <REMOVE>/bshpd_worker.go:485 +0x390

ERROR 10.176.227.235, <nil>
         map[ip:10.176.227.235 model:]
                request timeout (after 0 retries)
2021/01/23 09:11:33
Internal error: goroutine 365 [running]:
main.panicRecoverWorker(0x7d094f, 0xe, 0xc0013aa5d0, 0xc00005e480)
        <REMOVE>/panic_module.go:24 +0x8f
panic(0x76d3e0, 0xa095d0)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
main.(*WorkerDevice).GetDevice(0xc001ed6dc0)
        <REMOVE>/bshpd_worker.go:367 +0x85a
created by main.(*WorkerJoin).Run
        <REMOVE>/bshpd_worker.go:485 +0x390

goroutine 1 [chan receive]:
main.(*WorkerJoin).Run(0xc0001d0000)
        <REMOVE>/bshpd_worker.go:491 +0x425
main.JOBS()
        <REMOVE>/main23.go:26 +0x225
main.main()
        <REMOVE>/main23.go:33 +0x25

goroutine 6 [chan receive]:
github.com/ClickHouse/clickhouse-go.init.0.func1()
        /root/go/src/github.com/ClickHouse/clickhouse-go/bootstrap.go:50 +0x4b
created by github.com/ClickHouse/clickhouse-go.init.0
        /root/go/src/github.com/ClickHouse/clickhouse-go/bootstrap.go:47 +0x66
`

**Comment by vorlon001** [comment] 2021-01-23 06:57
@theraphim  how its fix in current relise for use "n, err = x.Conn.Read(x.rxBuf[:])"?

**Comment by TimRots** [comment] 2021-01-23 14:43
> can we, in spirit of being paranoidly backward-compatible, apply the patch I referred above? If yes I'll turn it into a PR. As you can see, it's just a refactoring which will make it impossible to even accidentally land on the code that does RecvFrom on connected socket.

@theraphim I like the idea of ensuring backwards-compatibility and love to give your pr some review. 
The only thing which kind of bothers me Is that I cannot replicate the issue reported by vorlon.

**Comment by theraphim** [comment] 2021-01-23 20:23
@TimRots I also can't understand what's going on here.
from the stack traces above I can only see 2 things:

1. The error handling is done in a way I've never seen before
2. Error message "request timeout (after 0 retries)" suggests that at some point in sendOneRequest a single timeout happens, but x.Retries == 0

Maybe it's something platform-specific? Read and ReadFrom have slightly different implementations under the hood at least on _unix, specifically RecvFrom calls .Recvfrom with flags==0 (no MSG_DONTWAIT, but probably it's irrelevant since fd is supposed to be nonblocking)

**Comment by vorlon001** [comment] 2021-01-24 08:34
@TimRots 

1) i fix my problem if not data from device
1.27.0 work, 1.28.0 work, 1.29.0 not work
result i fix my problem in 
current version helper.go
103:               retVal.Value = data[cursor:length]
on work worsion 1.28
103:               retVal.Value = string(data[cursor:length])

result return
version 1.29.0 
     []uint8 [76 105 110 117 120 32 83 86 69 84 76 79 69 95 83 69 67 95 49 32 50 46 54 46 51 50
version 1.28.0
    string "Linux 2.6.36.4brcmarm, Broadcom F......"
if FIX in my code

B2S := func (bs []uint8) string {
          b := make([]byte, len(bs))
          for i, v := range bs {
                    b[i] = byte(v)
          }
          return string(b)
}

tmp = B2S( variable.Value.([]uint8) ) 

2) I do not understand why returns []uint8?

3) "The error handling is done in a way I've never seen before
Error message "request timeout (after 0 retries)" suggests that at some point in sendOneRequest a single timeout happens, but x.Retries == 0" 
possible device did not return a response

4) I think I localized this problem
i use version 1.28.0
and testing version 1.29.0 and current version from git origin master

**Comment by vorlon001** [comment] 2021-01-24 08:38
@TimRots 
last question:
I do not understand why returns []uint8, it is OctetString?

current version helper.go and version 1.29.0
103: retVal.Value = data[cursor:length]

**Comment by SuperQ** [comment] 2021-01-24 09:05
1.27.0 and 1.28.0 contained a bug that incorrectly returned OctetString values as `string` and not `[]byte`. The correct behavior that was used in 1.26.0 and earlier was fixed in 1.29.0

OctetString values have many different encodings and are not always UTF-8 strings.

**Closed** 2021-01-24 09:33 UTC
