### ISSUE TITLE
Trap Listener panics on a v3 packet if not configured for v3

### ISSUE THREAD

**Issue by sponeil** [gosnmp/gosnmp#274] opened 2020-11-24 18:04 UTC
**Example Server Code:**
https://github.com/gosnmp/gosnmp/blob/master/examples/trapserver/main.go

**Example Client Code (change port to match server's port):**
https://github.com/gosnmp/gosnmp/blob/master/examples/trapsend_v3/main.go

**Note:** This may not seem like a valid test case, but if I have a server configured to listen for v1 and v2c traps only, it means my server will panic if any stray device attempts to send me a v3 packet. Inputs should always be validated, and servers should gracefully reject packets they can't read.

**This copy panics because sp.AuthenticationProtocol is uninitialized, and len() returns 0:**
	if flags&AuthNoPriv > 0 {
		copy(packet[cursor+2:cursor+len(macVarbinds[sp.AuthenticationProtocol])], macVarbinds[sp.AuthenticationProtocol][2:])
	}

**Panic Message:**
panic: runtime error: slice bounds out of range [49:47]

goroutine 8 [running]:
github.com/gosnmp/gosnmp.(*UsmSecurityParameters).unmarshal(0xc00009a1a0, 0xc00009a107, 0xc0000ae000, 0x91, 0x1000, 0x2f, 0x0, 0x0, 0x0)
	C:/Users/sean.oneil/go/pkg/mod/github.com/gosnmp/gosnmp@v1.28.0/v3_usm.go:897 +0x234f
github.com/gosnmp/gosnmp.(*GoSNMP).unmarshalV3Header(0xadd740, 0xc0000ae000, 0x91, 0x1000, 0x1b, 0xc0001461c0, 0x0, 0x0, 0x0)
	C:/Users/sean.oneil/go/pkg/mod/github.com/gosnmp/gosnmp@v1.28.0/v3.go:413 +0x18f0
github.com/gosnmp/gosnmp.(*GoSNMP).unmarshalHeader(0xadd740, 0xc0000ae000, 0x91, 0x1000, 0xc0001461c0, 0x0, 0x0, 0x0)
	C:/Users/sean.oneil/go/pkg/mod/github.com/gosnmp/gosnmp@v1.28.0/marshal.go:845 +0xbb3
github.com/gosnmp/gosnmp.(*GoSNMP).UnmarshalTrap(0xadd740, 0xc0000ae000, 0x91, 0x1000, 0x0, 0xc0001461c0)
	C:/Users/sean.oneil/go/pkg/mod/github.com/gosnmp/gosnmp@v1.28.0/trap.go:376 +0x19d
github.com/gosnmp/gosnmp.(*TrapListener).listenUDP(0xc0000a4000, 0xbb8899, 0xe, 0x0, 0x0)
	C:/Users/sean.oneil/go/pkg/mod/github.com/gosnmp/gosnmp@v1.28.0/trap.go:211 +0x637
github.com/gosnmp/gosnmp.(*TrapListener).Listen(0xc0000a4000, 0xbb8899, 0xe, 0x0, 0x0)
	C:/Users/sean.oneil/go/pkg/mod/github.com/gosnmp/gosnmp@v1.28.0/trap.go:351 +0x385
...

**Comment by clarkmcc** [comment] 2020-12-12 16:13
Thanks for the report, the example server and clients were very helpful. After digging around in the code for a bit, I must say I'm not very pleased with the unmarshalling implementation. It also looks like the original author felt the same. We could come up with a quick fix for this but I think the behavior you're seeing is indicative of a deeper problem, and we may want to solve that deeper problem.

https://github.com/gosnmp/gosnmp/blob/dc320dac5b53d95a366733fd95fb5851f2099387/trap.go#L133-L138

**Comment by sponeil** [comment] 2020-12-13 21:37
I agree 100%. However, time is short for me, and I decided to take a path
with less resistance. While testing SNMP traps with this library, I also
tested these other 2 libraries:

snmpgo (https://github.com/k-sone/snmpgo)
go-snmp (https://github.com/merinjo/go-snmp)

All 3 had issues, but go-snmp won me over for a few reasons. The first is
that its source code is quite a bit smaller and simpler, and if I need to
spend time refactoring/fixing/testing code in a third-party library, I
strongly prefer to start with the smallest and simplest one. The second is
that its design is much closer to the library I need. It actually has a
bunch of things I don't need, and removing them will make it even
smaller/simpler.

Basically, I need a library that does nothing more than build request
packets and parse response packets (including the v3
encryption/decryption). It can log errors, but it should not panic for any
reason. I need to deal with the sockets myself. To envision what I'm
thinking of, take a look at the "ParseTrap" function in
https://github.com/merinjo/go-snmp/blob/main/snmp.go. Then imagine it
refactored to look something like this (and imagine a similar function that
builds request packets for me):

(I apologize in advance for any mangling of the format due to me pasting
code into a reply email like this.)

// Parse does nothing more than parse any kind of SNMP packet (storing
parsed values or errors in "response").
// The "users" map is only required for v3 packets, and the map's key is
the v3 username (lower-case).
func (response *Response) Parse(packet []byte, users
map[string]*Credentials) {
    // Decode packet header
    var ok bool
    responseHeader, err := DecodeSequence(packet) // DecodeSequence needs a
good bit of work to prevent panics
    if err != nil {
        response.Error = fmt.Errorf("SNMP Parse Error: %#v", responseHeader)
        return
    }
    if len(responseHeader) < 2 { // Always test to avoid panics
        response.Error = fmt.Errorf("SNMP Parse Error - An SNMP packet
needs at least 2 header values, got %#v", responseHeader)
        return
    }
    if response.Version, ok = responseHeader[0].Value.(int); !ok { //
Always test to avoid panics
          response.Error = fmt.Errorf("SNMP Parse Error - Expected version
number, got %#v", responseHeader[0])
          return
    }
    if response.Version <= 1 {
        response.Version++ // Not necessary, but IMO it's nice to allow
clients to test for versions 1, 2, and 3 by literally checking for 1, 2,
and 3
    }

     var varbinds []BERVar
     switch response.Version { // Parse the headers, decode where
necessary, and find the start of the varbinds.
     case 1:
          // Not sure if I love or hate this if-else tree, but it seems to
simplify the code while I test every single value to avoid a panic due to a
malformed packet.
          if response.Community, ok = responseHeader[1].Value.(string); !ok
{
               err = fmt.Errorf("SNMP Parse Error - Expected v1 community
string, got %#v", responseHeader[1])
          } else if v1Header, ok := responseHeader[2].Value.([]BERVar); !ok
{
               err = fmt.Errorf("SNMP Parse Error - Expected v1 header, got
%#v", responseHeader[2])
          } else {
               response.Type = responseHeader[2].Type
               switch response.Type {
               case AsnTrap: // v1 trap packet
                    if len(v1Header) < 6 {
                         err = fmt.Errorf("SNMP Parse Error - v1 header too
short, got %#v", v1Header)
                    } else if response.Ent, ok = v1Header[0].Value.(Oid);
!ok {
                         err = fmt.Errorf("SNMP Parse Error - Expected v1
enterprise string, got %#v", v1Header[1])
                    } else if response.Agent, ok =
v1Header[1].Value.(string); !ok {
                         err = fmt.Errorf("SNMP Parse Error - Expected v1
agent string, got %#v", v1Header[1])
                    } else if response.Gen, ok = v1Header[2].Value.(int);
!ok {
                         err = fmt.Errorf("SNMP Parse Error - Expected v1
generic trap number, got %#v", v1Header[2])
                    } else if response.Spec, ok = v1Header[3].Value.(int);
!ok {
                         err = fmt.Errorf("SNMP Parse Error - Expected v1
specific trap number, got %#v", v1Header[2])
                    } else if response.T, ok = v1Header[4].Value.(uint64);
!ok {
                         err = fmt.Errorf("SNMP Parse Error - Expected v1
timestamp, got %#v", v1Header[2])
                    } else if varbinds, ok = v1Header[5].Value.([]BERVar);
!ok {
                         err = fmt.Errorf("SNMP Parse Error - Expected v1
varbinds, got %#v", v1Header[5])
                    }
               default: // v1 response packet
                    response.ID, ok = v1Header[0].Value.(int)
                    if len(v1Header) < 4 {
                         err = fmt.Errorf("SNMP Parse Error - v1 header too
short, got %#v", v1Header)
                    } else if varbinds, ok = v1Header[3].Value.([]BERVar);
!ok {
                         err = fmt.Errorf("SNMP Parse Error - Expected v1
varbinds, got %#v", v1Header[3])
                    }
               }
          }

     case 2:
         // Handle v2 (very similar to v1)...
     case 3:
         // Handle v3 (very different)...
     }

     // Check err, parse varbinds, and return
}


Please feel free to agree/disagree/question/argue/critique my ideas.

Thanks,
Sean

**Comment by TimRots** [comment] 2021-05-13 13:49
code from comment by @sponeil 

```go
// Parse does nothing more than parse any kind of SNMP packet (storing parsed values or errors in "response").
// The "users" map is only required for v3 packets, and the map's key is the v3 username (lower-case).
func (response *Response) Parse(packet []byte, users map[string]*Credentials) {
	// Decode packet header
	var ok bool
	responseHeader, err := DecodeSequence(packet)
	// DecodeSequence needs a good bit of work to prevent panics
	if err != nil {
		response.Error = fmt.Errorf("SNMP Parse Error: %#v", responseHeader)
		return
	}
	if len(responseHeader) < 2 { // Always test to avoid panics
		response.Error = fmt.Errorf("SNMP Parse Error - An SNMP packet needs at least 2 header values, got %#v", responseHeader)
		return
	}
	if response.Version, ok = responseHeader[0].Value.(int); !ok {
		//Always test to avoid panics
		response.Error = fmt.Errorf("SNMP Parse Error - Expected version number, got %#v", responseHeader[0])
		return
	}
	if response.Version <= 1 {
		response.Version++
		// Not necessary, but IMO it's nice to allow clients to test for versions 1, 2, and 3 by literally checking for 1, 2, and 3
	}

	var varbinds []BERVar
	switch response.Version { // Parse the headers, decode where necessary, and find the start of the varbinds.
	case 1:
		// Not sure if I love or hate this if-else tree, but it seems to simplify the code while I test every single value to avoid a panic due to a malformed packet.
		if response.Community, ok = responseHeader[1].Value.(string); !ok {
			err = fmt.Errorf("SNMP Parse Error - Expected v1 community string, got %#v", responseHeader[1])
		} else if v1Header, ok := responseHeader[2].Value.([]BERVar); !ok {
			err = fmt.Errorf("SNMP Parse Error - Expected v1 header, got %#v", responseHeader[2])
		} else {
			response.Type = responseHeader[2].Type
			switch response.Type {
			case AsnTrap: // v1 trap packet
				if len(v1Header) < 6 {
					err = fmt.Errorf("SNMP Parse Error - v1 header too short, got %#v", v1Header)
				} else if response.Ent, ok = v1Header[0].Value.(Oid); !ok {
					err = fmt.Errorf("SNMP Parse Error - Expected v1 enterprise string, got %#v", v1Header[1])
				} else if response.Agent, ok = v1Header[1].Value.(string); !ok {
					err = fmt.Errorf("SNMP Parse Error - Expected v1 agent string, got %#v", v1Header[1])
				} else if response.Gen, ok = v1Header[2].Value.(int); !ok {
					err = fmt.Errorf("SNMP Parse Error - Expected v1 generic trap number, got %#v", v1Header[2])
				} else if response.Spec, ok = v1Header[3].Value.(int); !ok {
					err = fmt.Errorf("SNMP Parse Error - Expected v1 specific trap number, got %#v", v1Header[2])
				} else if response.T, ok = v1Header[4].Value.(uint64); !ok {
					err = fmt.Errorf("SNMP Parse Error - Expected v1 timestamp, got %#v", v1Header[2])
				} else if varbinds, ok = v1Header[5].Value.([]BERVar); !ok {
					err = fmt.Errorf("SNMP Parse Error - Expected v1 varbinds, got %#v", v1Header[5])
				}
			default: // v1 response packet
				response.ID, ok = v1Header[0].Value.(int)
				if len(v1Header) < 4 {
					err = fmt.Errorf("SNMP Parse Error - v1 header too short, got %#v", v1Header)
				} else if varbinds, ok = v1Header[3].Value.([]BERVar); !ok {
					err = fmt.Errorf("SNMP Parse Error - Expected v1 varbinds, got %#v", v1Header[3])
				}
			}
		}

	case 2:
		// Handle v2 (very similar to v1)...
	case 3:
		// Handle v3 (very different)...
	}
	// Check err, parse varbinds, and return
}

```

**Comment by TimRots** [comment] 2021-05-13 14:23
The issue is reproducible on latest release

* [server](https://github.com/gosnmp/gosnmp/blob/master/examples/trapserver/main.go) listening for ``v2c`` trap
* [client](https://github.com/gosnmp/gosnmp/blob/master/examples/trapsend_v3/main.go) sending ``v3`` trap.
```
Packet sanity verified, we got all the bytes (145)
parseRawField: version
Parsed version 3
parseRawField: msgID
Parsed message ID 326200467
parseRawField: msgMaxSize
Parsed message max size 65535
parseRawField: msgFlags
parsed msg flags
parseRawField: msgSecurityModel
Parsed security model 3
parseRawField: msgAuthoritativeEngineID
Parsed authoritativeEngineID 31323334
parseRawField: msgAuthoritativeEngineBoots
Parsed authoritativeEngineBoots 0
parseRawField: msgAuthoritativeEngineTime
Parsed authoritativeEngineTime 0
parseRawField: msgUserName
Parsed userName user
parseRawField: msgAuthenticationParameters
Parsed authenticationParameters �2-�c�A�
panic: runtime error: slice bounds out of range [49:47]

goroutine 1 [running]:
github.com/gosnmp/gosnmp.(*UsmSecurityParameters).unmarshal(0xc00011f450, 0xc00011f407, 0xc00015f000, 0x91, 0x1000, 0x29, 0x10, 0x1156660, 0x126f058)
	/go/src/github.com/gosnmp/gosnmp/v3_usm.go:901 +0x12ee
github.com/gosnmp/gosnmp.(*GoSNMP).unmarshalV3Header(0x127a9a0, 0xc00015f000, 0x91, 0x1000, 0x1b, 0xc0001582a0, 0x7, 0x1156660, 0x126f058)
	/go/src/github.com/gosnmp/gosnmp/v3.go:414 +0x6ee
github.com/gosnmp/gosnmp.(*GoSNMP).unmarshalHeader(0x127a9a0, 0xc00015f000, 0x91, 0x1000, 0xc0001582a0, 0xc00015f000, 0x1000, 0x1000)
	/go/src/github.com/gosnmp/gosnmp/marshal.go:965 +0x6d5
github.com/gosnmp/gosnmp.(*GoSNMP).UnmarshalTrap(0x127a9a0, 0xc00015f000, 0x91, 0x1000, 0x0, 0xc00011d320)
	/go/src/github.com/gosnmp/gosnmp/trap.go:373 +0x9e
github.com/gosnmp/gosnmp.(*TrapListener).listenUDP(0xc00010e0f0, 0x11860cd, 0xc, 0x0, 0x0)
	/go/src/github.com/gosnmp/gosnmp/trap.go:210 +0x2c5
github.com/gosnmp/gosnmp.(*TrapListener).Listen(0xc00010e0f0, 0x11860cd, 0xc, 0xc000044f78, 0x1007745)
	/go/src/github.com/gosnmp/gosnmp/trap.go:348 +0x1dc
main.main()
	/workspace/gosnmp_debug/v3trap_crash_on_v2/server.go:37 +0x185
exit status 2
```

I'm working on a fix for 
* v3_usm.go: add check to unmarshal() for uninitialized AuthenticationProtocol
```go
       if len(macVarbinds[sp.AuthenticationProtocol]) == 0 {
               return 0, fmt.Errorf("error missing SNMPV3 AuthenticationProtocol")
       }
```
which will fix the panic:
```
Packet sanity verified, we got all the bytes (145)
parseRawField: version
Parsed version 3
parseRawField: msgID
Parsed message ID 1584922215
parseRawField: msgMaxSize
Parsed message max size 65535
parseRawField: msgFlags
parsed msg flags
parseRawField: msgSecurityModel
Parsed security model 3
parseRawField: msgAuthoritativeEngineID
Parsed authoritativeEngineID 31323334
parseRawField: msgAuthoritativeEngineBoots
Parsed authoritativeEngineBoots 0
parseRawField: msgAuthoritativeEngineTime
Parsed authoritativeEngineTime 0
parseRawField: msgUserName
Parsed userName user
parseRawField: msgAuthenticationParameters
Parsed authenticationParameters ��n�����1��
UnmarshalTrap: error missing SNMPV3 AuthenticationProtocol
```

* marshal.go: add check to unmarshalHeader to discard snmp packets that have a different version than what we are listening for:
```go
       if response.Version != x.Version {
               return 0, fmt.Errorf("discarded v%v packet while listening for %v", response.Version, x.Version)
       }
```

results in discarding the packet:
```
Packet sanity verified, we got all the bytes (145)
parseRawField: version
Parsed version 3
UnmarshalTrap: discarded v3 packet while listening for 2c
```

Having the above fixes results in issues with the tests, refactoring these will take some more time.

**Closed** 2021-10-09 08:37 UTC
Labels: bug
