### ISSUE TITLE
Set snmp problem

### ISSUE THREAD

**Issue by maxkermarrec** [gosnmp/gosnmp#263] opened 2020-11-06 16:44 UTC
Hello,

We have possibly found a bug on your library gosnmp.

When we realize a set snmp on the interface of a switch, we sometimes never receive an answer even though a tcpdump call show one that was well received as you can see on the first screenshot.

![wireshark](https://user-images.githubusercontent.com/44021489/98391493-00a52a80-2057-11eb-808e-365c0b33d408.PNG)

On this second screenshot, you can see the timeOut that even happens if it is set to 20 seconds

![20201106BugSNMP1](https://user-images.githubusercontent.com/44021489/98391522-0ef34680-2057-11eb-99e1-d524b35b3314.PNG)

Thanks for your attention.

**Comment by TimRots** [comment] 2020-11-15 23:04
hi @maxkermarrec , would it be possible to share the pcap and some more details on your setup?

**Comment by maxkermarrec** [comment] 2020-11-16 09:48
Hello, I don't have the original file but i reproduced the bug and made another pcap file.

Here you can see the answer being sent 

![20201116ProblemSNMP](https://user-images.githubusercontent.com/44021489/99237026-3c2eba00-27f8-11eb-96ee-7d5e882b8743.PNG)

And here the same error in our logs

![20201116ProblemSNMPLogsDockyard](https://user-images.githubusercontent.com/44021489/99237158-684a3b00-27f8-11eb-80ff-ad9e02bbabe6.PNG)

And here is the pcap file :

[PCAPFile.zip](https://github.com/gosnmp/gosnmp/files/5545414/PCAPFile.zip)

We are getting datas from a switch in SNMP over the internet with a VPN and all the gets work fine, we are only having problems with the set. They always works but about half of the time we don't get the answer by your library even though the device answer the set and the admin status of the interface has been changed.

PS: I'm sorry for my average english, it is not my native language.

Thank you for your time.

**Comment by TimRots** [comment] 2020-11-17 17:35
Hi @maxkermarrec. 

What OS and (go)snmp version are you using to poll the switch?

**Comment by maxkermarrec** [comment] 2020-11-18 08:10
Hello,
I am using a linux OS inside a docker container and the snmp version is v2c.
We are actually using gosnmp v1.27.0.
Thanks again for your time.

**Comment by TimRots** [comment] 2020-11-18 16:38
Thanks for the additional info @maxkermarrec 

I have checked the pcap you've shared, and the only thing that catches my attention is that you are facing a possible race situation:

![Screenshot 2020-11-18 at 01 33 44](https://user-images.githubusercontent.com/8184932/99559191-cb88c880-29c4-11eb-9ccf-cea9174af13d.png)

Can you see a similar pattern for requests that do succeed?

**Comment by maxkermarrec** [comment] 2020-11-23 09:07
Hello,
I'm not quite sure about it but I think that I found a situation where it doesn't work that contradict your hypothesis. Here are the different files : 

![20201119LogsSetSNMPFailure](https://user-images.githubusercontent.com/44021489/99944354-05feb680-2d73-11eb-83fa-76444c457e63.PNG)

![20201119SetSNMPFailureTcpDUMP](https://user-images.githubusercontent.com/44021489/99944366-0a2ad400-2d73-11eb-8507-6f576e053453.PNG)

Here you can see a success if that could help :

![20201119LogsSetSuccess](https://user-images.githubusercontent.com/44021489/99944397-1adb4a00-2d73-11eb-85cf-32d63b972145.PNG)

 and here is the pcap file :

[20201119capture1.zip](https://github.com/gosnmp/gosnmp/files/5581848/20201119capture1.zip)

In this situation, you can see that the call is in no conflict with another one and it still failed to give me an answer. I would appreciate your response on this subject to better understand the problem at hand here. 

Thanks a lot for giving me so much of your time.

**Comment by TimRots** [comment] 2020-11-23 15:09
Thank you for the update and detailed information @maxkermarrec. I will review the pcap you submitted when I have some more time on hands later this week.

**Comment by maxkermarrec** [comment] 2020-12-03 09:09
Hello,
Did you had time to spend on the problem ?
Thank you in advance.

**Comment by TimRots** [comment] 2020-12-07 12:00
@maxkermarrec Still have not been able to reproduce this behavior. 

Would you be able to test your code against the latest release? If you still see the issue happening you would need to share some of your code (off-site?)

**Comment by TimRots** [comment] 2020-12-10 23:47
Hi @maxkermarrec, hope everything is going well.

Would you be able to let me know if the issue you mentioned persists when building from this branch: https://github.com/TimRots/gosnmp/tree/fix/263/treat-empty-data-in-response-as-oid

**Comment by maxkermarrec** [comment] 2020-12-14 16:10
Hello again @TimRots,
I tried on the latest release and on the branch you gave me. Unfortunately, I had the exact same problem. I also can't share code with you because my company doesn't allow it. I will have to find another way to know if the set worked.

Thanks a lot for all the time that you gave me and for your help.

**Comment by TimRots** [comment] 2020-12-14 20:53
Hi @maxkermarrec. 

Sorry to hear the issue is not resolved for you. It kind of bothers me that we did not manage to find anything substantial for your issue.
Can you close this issue for the time being? Please feel free to re-open when you do find a way to reliably reproduce the issue and I'm happy to continue looking into this.

**Closed** 2020-12-15 08:06 UTC

**Comment by svfreitas** [comment] 2023-09-21 01:23
> Hello again @TimRots, I tried on the latest release and on the branch you gave me. Unfortunately, I had the exact same problem. I also can't share code with you because my company doesn't allow it. I will have to find another way to know if the set worked.
> 
> Thanks a lot for all the time that you gave me and for your help.

Hi @maxkermarrec 

I am facing exactly the same issue, did you find a way to fix it?

Thanks
Sergio
