### ISSUE TITLE
snmp v2 trap server ceceive v3 trap packet occur panic

### ISSUE THREAD

**Issue by reli440** [gosnmp/gosnmp#347] opened 2021-06-21 03:13 UTC
when a snmp v2 trap listen received a v3 trap packet,it's occuring follow error:

panic: runtime error: slice bounds out of range [63:61]
goroutine 53 [running]:
github.com/gosnmp/gosnmp.(*UsmSecurityParameters).unmarshal(0xc0003acc30, 0xc0003acc03, 0xc00065b000, 0xcb, 0x1000, 0x36, 0x10, 0x2499120, 0x448b8d8)
#011/root/go/pkg/mod/github.com/gosnmp/gosnmp@v1.32.0/v3_usm.go:975 +0x12ed
github.com/gosnmp/gosnmp.(*GoSNMP).unmarshalV3Header(0xc000496500, 0xc00065b000, 0xcb, 0x1000, 0x1b, 0xc000230380, 0x7, 0x2499120, 0x448b8d8)
#011/root/go/pkg/mod/github.com/gosnmp/gosnmp@v1.32.0/v3.go:414 +0x74f
github.com/gosnmp/gosnmp.(*GoSNMP).unmarshalHeader(0xc000496500, 0xc00065b000, 0xcb, 0x1000, 0xc000230380, 0xc000079e60, 0x60529d, 0xc0000100d0)
#011/root/go/pkg/mod/github.com/gosnmp/gosnmp@v1.32.0/marshal.go:965 +0x675
github.com/gosnmp/gosnmp.(*GoSNMP).UnmarshalTrap(0xc000496500, 0xc00065b000, 0xcb, 0x1000, 0x0, 0xc00009f200)
#011/root/go/pkg/mod/github.com/gosnmp/gosnmp@v1.32.0/trap.go:373 +0xa5
github.com/gosnmp/gosnmp.(*TrapListener).listenUDP(0xc0001803c0, 0xc0005809b7, 0x5, 0x0, 0x0)
#011/root/go/pkg/mod/github.com/gosnmp/gosnmp@v1.32.0/trap.go:210 +0x2ae
github.com/gosnmp/gosnmp.(*TrapListener).Listen(0xc0001803c0, 0xc0005809b1, 0xb, 0x0, 0x0)
#011/root/go/pkg/mod/github.com/gosnmp/gosnmp@v1.32.0/trap.go:348 +0x1dc

suggest：It is recommended to judge the version of snmp first, and ignore packets with inconsistent versions

**Comment by TimRots** [comment] 2021-06-21 06:29
Duplicate of #274

**Closed by TimRots** 2021-06-21 06:29 UTC
